### ISSUE TITLE
wants insight

### ISSUE THREAD

**Issue by Kaustubh2904** [EhabHelaly/Air_Hockey_Game_Robot#1]
Hi, can u please guide me on this project I am trying to make something similar to this but with python and there are some things that i would like to ask about the project ?

**Comment by EhabHelaly** [comment]
Sure,
What do you want to ask about?

**Comment by Kaustubh2904** [comment]
thanks for reaching out, i had a doubt regarding where it's something completely software based or does it actually helps a user to control robots that will play air hockey irl ?

**Comment by EhabHelaly** [comment]
Yes this is for robot application

System is as follows:
- USB Camera
- AVR microcintroller or arduino
- 2 stepper motors
- TTL device (UART)
- PC

Sequence:
- Camera is mounted on top of air hocky table
- this app captures image from camera using opencv
- then it does needed processing
- then it sends data to uc over TTL device
- uc SW controllers both stepper motors that are holding the robot paddle and move it to correct position
-

**Comment by Kaustubh2904** [comment]
got the idea thanks a lot. What i am doing is just using opencv to play the game using gestures
